title:              Dayeong Kim / 김다영
email:              dayeong.kim.edu@gmail.com
description:        
author:             Dayeong Kim
baseurl:            "https:/github.com/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   
github_username:    kdy0406
facebook_username:  
instagram_username:  
linkedin_username:  dayeongkim0406

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
